apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: view_namespace_cluster_role_binding
subjects:
- kind: ServiceAccount
  name: eks-ram-alert
  namespace: eks-ram-alert
roleRef:
  kind: ClusterRole
  name: view_namespace_cluster_role
  apiGroup: rbac.authorization.k8s.io